version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Dynasor.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./src/Dynasor.csproj
clone_depth: 1
test_script:
  - cmd: dotnet restore ./tests/Dynasor.Test/Dynasor.Test.csproj --verbosity m
  - cmd: cd Dynasor.Test
  - cmd: dotnet test
on_finish :
deploy: off